# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "usb_storage" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/8535353a-3288-442b-882f-b12eb83f5a76";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/F67C-1200";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ ];

  # hardware.asahi.peripheralFirmwareDirectory = ./firmware;
  hardware.asahi.peripheralFirmwareDirectory = pkgs.requireFile {
    name = "asahi-firmware";
    hashMode = "recursive";
    hash = "sha256-rupaV9zBoBUkLTxVqqMJ6qz841s9UCwGZYxmJ1NII6o=";
    message = ''
      nix-store --add-fixed sha256 --recursive <path-to-asahi-esp>/asahi-firmware
    '';
  };

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}
