---
volumes:
  etc_pihole-unbound-vlan20:
  etc_pihole_dnsmasq-unbound-vlan20:
  etc_pihole-unbound-vlan99:
  etc_pihole_dnsmasq-unbound-vlan99:
  etc_pihole-unbound-vlan207:
  etc_pihole_dnsmasq-unbound-vlan207:

services:
  pihole-vlan20:
    container_name: pihole-vlan20
    image: aleksanderbl/pihole-unbound:2024.07.0
    hostname: ${HOSTNAME}
    domainname: ${DOMAIN_NAME}
    dns:
      - 127.0.0.1
    ports:
      # - 443:443/tcp  ### Uncomment to use without proxy
      - 53:53/tcp
      - 53:53/udp
      - 908:80/tcp  ## Uncomment to use without proxy   #Allows use of different port to access pihole web interface when other docker containers use port 80
      - 5335:5335 # Uncomment to enable unbound access on local server
      # - 22/tcp # Uncomment to enable SSH
    environment:
      - FTLCONF_LOCAL_IPV4=${FTLCONF_LOCAL_IPV4}
      - TZ=Europe/Copenhagen
      - WEBPASSWORD=${WEBPASSWORD}
      # - WEBTHEME=${WEBTHEME:-default-dark}
      - REV_SERVER=true
      - REV_SERVER_TARGET=${REV_SERVER_TARGET}
      - REV_SERVER_DOMAIN=${REV_SERVER_DOMAIN}
      - REV_SERVER_CIDR=${REV_SERVER_CIDR}
      - PIHOLE_DNS_=127.0.0.1#5335
      # - PIHOLE_DNS_=1.1.1.1
      - DNSSEC="true"
      - DNSMASQ_LISTENING=all
      - VIRTUAL_HOST=pi.hole
    volumes:
      - ./03-custom-vlan20.conf:/etc/dnsmasq.d/03-custom.conf
      - ./internal-vlan20.list:/etc/pihole/custom.list
      # - etc_pihole-unbound:/etc/pihole:rw
      # - etc_pihole_dnsmasq-unbound:/etc/dnsmasq.d:rw
    restart: unless-stopped
    # security_opt:
    #   - no-new-privileges:true
    networks:
      - proxy
    labels:
      com.centurylinklabs.watchtower.monitor-only: true

      ## Traefik config ##
      traefik.enable: true
      traefik.http.routers.pihole-vlan20.entrypoints: http
      traefik.http.routers.pihole-vlan20.rule: Host(`pihole-vlan20.local.aleksanderbl.dk`)
      traefik.http.middlewares.pihole-vlan20-https-redirect.redirectscheme.scheme: https
      traefik.http.middlewares.pihole-vlan20-admin.addprefix.prefix: /admin
      traefik.http.routers.pihole-vlan20.middlewares: pihole-vlan20-https-redirect
      traefik.http.routers.pihole-vlan20-secure.entrypoints: https
      traefik.http.routers.pihole-vlan20-secure.rule: Host(`pihole-vlan20.local.aleksanderbl.dk`)
      traefik.http.routers.pihole-vlan20-secure.tls: true
      traefik.http.routers.pihole-vlan20-secure.middlewares: pihole-vlan20-admin
      # traefik.http.routers.pihole-vlan20-secure.middlewares: pihole-vlan20-redirect
      traefik.http.routers.pihole-vlan20-secure.service: pihole-vlan20
      traefik.http.services.pihole-vlan20.loadbalancer.server.port: 80
      traefik.docker.network: proxy

  pihole-vlan99:
    container_name: pihole-vlan99
    image: aleksanderbl/pihole-unbound:2024.07.0
    hostname: ${HOSTNAME}
    domainname: ${DOMAIN_NAME}
    dns:
      - 127.0.0.1
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 909:80/tcp
      - 5336:5335
    environment:
      - FTLCONF_LOCAL_IPV4=${FTLCONF_LOCAL_IPV4}
      - TZ=Europe/Copenhagen
      - WEBPASSWORD=${WEBPASSWORD}
      - REV_SERVER=true
      - REV_SERVER_TARGET=${REV_SERVER_TARGET}
      - REV_SERVER_DOMAIN=${REV_SERVER_DOMAIN}
      - REV_SERVER_CIDR=${REV_SERVER_CIDR}
      - PIHOLE_DNS_=127.0.0.1#5335
      - DNSSEC="true"
      - DNSMASQ_LISTENING=all
      - VIRTUAL_HOST=pi.hole
    volumes:
      - ./03-custom-vlan99.conf:/etc/dnsmasq.d/03-custom.conf
      - ./internal-vlan99.list:/etc/pihole/custom.list
    restart: unless-stopped
    networks:
      - proxy
    labels:
      com.centurylinklabs.watchtower.monitor-only: true

      ## Traefik config ##
      traefik.enable: true
      traefik.http.routers.pihole-vlan99.entrypoints: http
      traefik.http.routers.pihole-vlan99.rule: Host(`pihole-vlan99.local.aleksanderbl.dk`)
      traefik.http.middlewares.pihole-vlan99-https-redirect.redirectscheme.scheme: https
      traefik.http.middlewares.pihole-vlan99-admin.addprefix.prefix: /admin
      traefik.http.routers.pihole-vlan99.middlewares: pihole-vlan99-https-redirect
      traefik.http.routers.pihole-vlan99-secure.entrypoints: https
      traefik.http.routers.pihole-vlan99-secure.rule: Host(`pihole-vlan99.local.aleksanderbl.dk`)
      traefik.http.routers.pihole-vlan99-secure.tls: true
      traefik.http.routers.pihole-vlan99-secure.middlewares: pihole-vlan99-admin
      traefik.http.routers.pihole-vlan99-secure.service: pihole-vlan99
      traefik.http.services.pihole-vlan99.loadbalancer.server.port: 80
      traefik.docker.network: proxy

  pihole-vlan207:
    container_name: pihole-vlan207
    image: aleksanderbl/pihole-unbound:2024.07.0
    hostname: ${HOSTNAME}
    domainname: ${DOMAIN_NAME}
    dns:
      - 127.0.0.1
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 910:80/tcp
      - 5337:5335
    environment:
      - FTLCONF_LOCAL_IPV4=${FTLCONF_LOCAL_IPV4}
      - TZ=Europe/Copenhagen
      - WEBPASSWORD=${WEBPASSWORD}
      - REV_SERVER=true
      - REV_SERVER_TARGET=${REV_SERVER_TARGET}
      - REV_SERVER_DOMAIN=${REV_SERVER_DOMAIN}
      - REV_SERVER_CIDR=${REV_SERVER_CIDR}
      - PIHOLE_DNS_=127.0.0.1#5335
      - DNSSEC="true"
      - DNSMASQ_LISTENING=all
      - VIRTUAL_HOST=pi.hole
    volumes:
      - ./03-custom-vlan207.conf:/etc/dnsmasq.d/03-custom.conf
      - ./internal-vlan207.list:/etc/pihole/custom.list
    restart: unless-stopped
    networks:
      - proxy
    labels:
      com.centurylinklabs.watchtower.monitor-only: true

      ## Traefik config ##
      traefik.enable: true
      traefik.http.routers.pihole-vlan207.entrypoints: http
      traefik.http.routers.pihole-vlan207.rule: Host(`pihole-vlan207.local.aleksanderbl.dk`)
      traefik.http.middlewares.pihole-vlan207-https-redirect.redirectscheme.scheme: https
      traefik.http.middlewares.pihole-vlan207-admin.addprefix.prefix: /admin
      traefik.http.routers.pihole-vlan207.middlewares: pihole-vlan207-https-redirect
      traefik.http.routers.pihole-vlan207-secure.entrypoints: https
      traefik.http.routers.pihole-vlan207-secure.rule: Host(`pihole-vlan207.local.aleksanderbl.dk`)
      traefik.http.routers.pihole-vlan207-secure.tls: true
      traefik.http.routers.pihole-vlan207-secure.middlewares: pihole-vlan207-admin
      traefik.http.routers.pihole-vlan207-secure.service: pihole-vlan207
      traefik.http.services.pihole-vlan207.loadbalancer.server.port: 80
      traefik.docker.network: proxy

networks:
  proxy:
    external: false
