site_name: Aleksander's Nix Config
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - content.code.copy

# Point to a subdirectory for source files
docs_dir: content
# Put site output outside the docs dir
site_dir: ../site

nav:
  - Home: ../README.md
  - Documentation:
    - browser-signings.md
    - manual-things.md
    - to-do.md