site_name: Aleksander's Nix Config
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - content.code.copy

# Point directly to docs directory
docs_dir: .
site_dir: _site

nav:
  - Home: ../README.md
  - Documentation:
    - content/