name: Nix Colmena Deployment

on:
  push:
    branches: [ main ]
    paths-ignore:
      - "docs/**"
      - ".github/workflows/docs.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Setup Nix Cache
        uses: DeterminateSystems/flakehub-cache-action@main

      - name: Check Flake Inputs
        run: nix flake check

      - name: Setup Tailscale
        uses: tailscale/github-action@v2
        with:
            hostname: Github-actions
            oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
            oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
            tags: tag:nix-ci

      - name: Apply config to k3s-1
        run: ssh root@k3s-1 'cd /etc/nixos && git pull && nixos-rebuild switch --flake .#k3s-1'

      - name: Apply config to k3s-2
        run: ssh root@k3s-2 'cd /etc/nixos && git pull && nixos-rebuild switch --flake .#k3s-2'

      - name: Apply config to k3s-3
        run: ssh root@k3s-3 'cd /etc/nixos && git pull && nixos-rebuild switch --flake .#k3s-3'
